app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('template');
});

Route::resource('produit','ProduitController');
Route::resource('reference','ReferenceController');

app/filters.php
<?php

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function($request)
{
	//
});


App::after(function($request, $response)
{
	//
});

/*
|--------------------------------------------------------------------------
| Authentication Filters
|--------------------------------------------------------------------------
|
| The following filters are used to verify that the user of the current
| session is logged into this application. The "basic" filter easily
| integrates HTTP Basic authentication for quick, simple checking.
|
*/

Route::filter('auth', function()
{
	if (Auth::guest())
	{
		if (Request::ajax())
		{
			return Response::make('Unauthorized', 401);
		}
		else
		{
			return Redirect::guest('login');
		}
	}
});


Route::filter('auth.basic', function()
{
	return Auth::basic();
});

/*
|--------------------------------------------------------------------------
| Guest Filter
|--------------------------------------------------------------------------
|
| The "guest" filter is the counterpart of the authentication filters as
| it simply checks that the current user is not logged in. A redirect
| response will be issued if they are, which you may freely change.
|
*/

Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function()
{
	if (Session::token() !== Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

app/models/Produit.php
<?php

class Produit extends Eloquent {

	public $timestamps = false;  //désactive created_at & updated_at

	protected $table = 'produit';
	protected $primaryKey = 'idProduit';

	

    
}

app/models/Reference.php
<?php

class Reference extends Eloquent {

	public $timestamps = false;  //désactive created_at & updated_at

	protected $table = 'reference';
	protected $primaryKey = 'idReference';
	

    
}

app/controllers/BaseController.php
<?php

class BaseController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

app/controllers/ProduitController.php
<?php

class ProduitController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
            $produits = Produit::all();
            
            /*$itemIdentique = array();
            foreach($produits as $prod){
                $doublon = DB::table(DB::raw('produit as p'))
                     ->select(array('p.date', 'p.heure', 'p.valeurScan', 'p.typeProduit', DB::raw('p.count(*) as item_count')))
                     ->groupBy(array('p.date', 'p.heure', 'p.valeurScan', 'p.typeProduit'))
                     ->get();
                var_dump($doublon);
            }*/
            return View::make('RecupDonnees')
			->with('produits', $produits);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
            
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($idProduit)
	{
            $produit = Produit::find($idProduit);
            return View::make('AjoutTypeProduit')
                    ->with('produit', $produit);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($idProduit)
	{
            $produit = Produit::find($idProduit);
			
            if ( Request::get('typeProduit') )
            {
                $produit->typeProduit = Request::get('typeProduit');
            }
            $produit->save();
            return Redirect::route('produit.index', $idProduit)->with('ok', 'La modification a été prise en compte.');
		
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/controllers/ReferenceController.php
<?php

class ReferenceController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
            
            return View::make('RechercheTypeProduit');
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
            $uneValeurScan = Request::get('valeurScan');
            
            $references = Reference::where('valeurScan', '=', $uneValeurScan)->get();
            return View::make('ReponseTypeProduit')
                    ->with('references', $references);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/AjoutTypeProduit.blade.php
@extends('template')

@section('contenu')

<!-- Formulaire de nouvelle saisie -->
<div class='col-xs-12 col-sm-9 col-ms-offset-1 col-md-9 col-lg-6 col-lg-offset-2'>
    @if(Session::has('ok'))
            <div class="alert alert-success">{{ Session::get('ok') }}</div>
    @else
        @if(Session::has('ko'))
            <div class="alert alert-danger">{{ Session::get('ko') }}</div>
        @else
            <div class="alert alert-material-indigo-100"></div>
        @endif
    @endif
    <div class='panel-heading'>
        <div class='form-horizontal' >
            <h5 class='panel-title'><strong>Ajout du type produit pour le produit : {{ $produit->idProduit }}</strong></h5>
        </div>
    </div>
    <div class="panel panel-info">
        {{ Form::open(array('url' => 'produit/' . $produit->idProduit, 'method' => "put")) }}

        <table class='table table-bordered table-condensed'>
            <tr bgcolor="#FFFFFF ">
                <td>
                    <div class="form-group {{ $errors->has('typeProduit') ? 'has-error has-feedback' : '' }}">
                        <label class="col-xs-12 col-sm-12 col-md-12 col-lg-12 control-label"></font>Type du produit :</label><br />
                        {{ Form::text('typeProduit', $produit->typeProduit, array('class' => 'form-control input-normal' ,  'placeholder' => 'Insérer le type de produit')) }}
                        <strong class="text-danger">{{ $errors->first('typeProduit') }}</strong>
                    </div>
                </td>
            </tr>

            <tr bgcolor="#EFF5FB"> 
                <td colspan=6>
                    <p align="center"></br>
                        {{ Form::submit('Valider', array('class' => 'btn btn-info pull-center', 'style' => 'cursor:hand;' , 'title'=>'Valider')) }}
                    </p>
                </td>
            </tr>
        </table>
        {{ Form::close() }}
    </div>
</div>	
@stop

app/views/RechercheTypeProduit.blade.php
@extends('template')

@section('contenu')

<div class='col-xs-12 col-sm-9 col-ms-offset-1 col-md-9 col-lg-6 col-lg-offset-2'>
    @if(Session::has('ok'))
            <div class="alert alert-success">{{ Session::get('ok') }}</div>
    @else
        @if(Session::has('ko'))
            <div class="alert alert-danger">{{ Session::get('ko') }}</div>
        @else
            <div class="alert alert-material-indigo-100"></div>
        @endif
    @endif
    <div class='panel-heading'>
        <div class='form-horizontal' >
            <h5 class='panel-title'><strong>Rechercher le type produit</strong></h5>
        </div>
    </div>
    <div class="panel panel-info">
        {{ Form::open(array('url' => 'reference', 'method' => "post")) }}

        <table class='table table-bordered table-condensed'>
            <tr bgcolor="#FFFFFF ">
                <td>
                    <div class="form-group {{ $errors->has('valeurScan') ? 'has-error has-feedback' : '' }}">
                        <label class="col-xs-12 col-sm-12 col-md-12 col-lg-12 control-label"></font>Valeur Scan :</label><br />
                        {{ Form::text('valeurScan', null, array('class' => 'form-control input-normal' ,  'placeholder' => 'Insérer la valeur Scan')) }}
                        <strong class="text-danger">{{ $errors->first('valeurScan') }}</strong>
                    </div>
                </td>
            </tr>

            <tr bgcolor="#EFF5FB"> 
                <td colspan=6>
                    <p align="center"></br>
                        {{ Form::submit('Valider', array('class' => 'btn btn-info pull-center', 'style' => 'cursor:hand;' , 'title'=>'Valider')) }}
                    </p>
                </td>
            </tr>
        </table>
        {{ Form::close() }}
    </div>
</div>	
@stop

app/views/RecupDonnees.blade.php
@extends('template')

@section('contenu')

<!-- --------------------------------------------
   Lister Astreintes
 -------------------------------------------- -->

<div class='container-fluid'>
    <div class='row'>
        <div class='col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1'>
            @if(Session::has('ok'))
                <div class="alert alert-success">{{ Session::get('ok') }}</div>
            @else
                <div class="alert"></div>
            @endif
            <div style="border-color:#D8D8D8" class="panel panel-default">
                <h4 style="padding-left:1em; padding-top:1em;">
                    <strong><span class="fa fa-clock-o fa-fw"></span> Récupération des données </strong>
                </h4><br />
                <div class="table-responsive" style="padding-left:1em; padding-right:1em; padding-bottom:1em;">
                    <table id="tab_produit" class="table table-striped table-bordered table-condensed dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
                        <thead>
                            <tr>
                                <td><strong>Date</strong></td>
                                <td><strong>Heure</strong></td>
                                <td><strong>Valeur scan</strong></td>
                                <td><strong>Type de produit</strong></td>
                                <td><strong>Nombre de produit identique</strong></td>
                                <td><i>Ajouter type de produit</i></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($produits as $valeur)
                                 @if (isset($valeur['idProduit']))
                                    {{ Form::hidden('idProduit', $valeur['idProduit'],array('id'=>'idProduit', 'name' =>'idProduit', 'class' => 'form-control input-sm')) }}
                                    <tr>
                                        @if (isset($valeur['date']))
                                            <td>{{ date('d/m/Y', strtotime($valeur['date'])) }}</td>
                                        @endif
                                        @if (isset($valeur['heure']))
                                            <td>{{ date('H:i', strtotime($valeur['heure'])) }}</td>
                                        @endif
                                        @if (isset($valeur['valeurScan']))
                                            <td>{{ $valeur['valeurScan'] }} </td>
                                        @else
                                            <td></td>
                                        @endif
                                        @if (isset($valeur['typeProduit']))
                                            <td>{{ $valeur['typeProduit'] }}</td>
                                        @else
                                            <td></td>
                                        @endif
                                        
                                        <td>{{ "a calculer" }}</td>
                                        <td style='width:5px'>  
                                            <a href="{{URL::to('produit/' . $valeur->idProduit.'/edit')}}" class='btn btn-default ' title="Modifier"><i class="glyphicon glyphicon-pencil text-success"></i></a>
                                        </td>
                                    </tr>
                                @endif  
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@stop

@section('js')
    {{ HTML::script('js/produitsDataTable.js') }}
    {{ HTML::script('js/moment.min.js') }}
    {{ HTML::script('js/moment-with-locales.min.js') }}
    {{ HTML::script('js/datetime-moment.js') }}
@stop

app/views/ReponseTypeProduit.blade.php
@extends('template')

@section('contenu')

<!-- --------------------------------------------
   Lister Astreintes
 -------------------------------------------- -->

<div class='container-fluid'>
    <div class='row'>
        <div class='col-xs-12 col-sm-10 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1'>
            @if(Session::has('ok'))
                <div class="alert alert-success">{{ Session::get('ok') }}</div>
            @else
                <div class="alert"></div>
            @endif
            <div style="border-color:#D8D8D8" class="panel panel-default">
                <h4 style="padding-left:1em; padding-top:1em;">
                    <strong><span class="fa fa-clock-o fa-fw"></span> Types de produit correspondant </strong>
                </h4><br />
                <div class="table-responsive" style="padding-left:1em; padding-right:1em; padding-bottom:1em;">
                    <table id="tab_typeproduit" class="table table-striped table-bordered table-condensed dataTable no-footer" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
                        <thead>
                            <tr>
                                <td><strong>Types de produit</strong></td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($references as $valeur)
                                @if (isset($valeur['idReference']))
                                    {{ Form::hidden('idReference', $valeur['idReference'],array('id'=>'idReference', 'name' =>'idReference', 'class' => 'form-control input-sm')) }}
                                    <tr>
                                        @if (isset($valeur['typeProduit']))
                                            <td>{{ $valeur['typeProduit'] }}</td>
                                        @else
                                            <td>Aucun type correspondant</td>
                                        @endif
                                    </tr>
                                @endif  
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@stop

@section('js')
    {{ HTML::script('js/typeproduitDataTable.js') }}
@stop

app/views/template.blade.php
<!doctype html>
<html lang="fr">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>Trackeur</title>
	<link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
    {{ HTML::style('css/bootstrap.min.css') }}
    {{ HTML::style('css/bootstrap-theme.min.css') }}
    {{ HTML::style('css/jquery.dataTables.min.css') }}
    {{ HTML::style('css/jquery.dataTables_themeroller.css') }}
    {{ HTML::style('css/dataTables.bootstrap.css') }}
    {{ HTML::style('css/common.css') }}
    
	<style>
		body {
		    padding-top: 60px;
		    padding-bottom: 30px;
		    font-size: 12px;
		}
		.table {
			margin-bottom: 0px;
			font-size: small;
		}
	</style>
</head>
<body style="background-color:#F2F2F2"> <!-- FFF7EE FFF5EF FFFDF3  -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse" style="background-color:#1C1C1C;">
           <ul class="nav navbar-nav navbar-left">	
                <li class="dropdown">
                    <a class="navbar-brand" href="{{route('produit.index')}}"><font color="white">Récupération des données</font></a>
                </li>
            </ul>
            <ul class="nav navbar-nav">	
                <li class="dropdown">
                    <a class="navbar-brand" href="{{route('reference.index')}}"><font color="white">Recherche Type Produit</font></a>
                </li>
            </ul>
        </div>
    </div>
	
	@yield('contenu')
	
    <footer>
        {{ HTML::script('js/jquery-2.1.1.min.js') }}
        {{ HTML::script('js/jquery.dataTables.min.js') }}
        {{ HTML::script('js/bootstrap.min.js') }}
        {{ HTML::script('js/common.js') }}

        @yield('js')	
    </footer>
</body>
</html>